### PR TITLE
Fully implemented case where Type of SQLCommand is Text

### PR DESCRIPTION
**Pull request by birbilis**
apart from the implementation for Text type of SQLCommand, also refactored code for readability and added some TODO notes on how to address NULL value issue (https://github.com/jphellemons/CommandAsSql/issues/1)

### CODE REVIEW

**Comment by jphellemons** [comment]
Big change. Thanks! Will take a look at it asap. Would have been easier for me to check, if you would have made more smaller commits. But thanks! 👍

**Comment by birbilis** [comment]
It's a pity GitHub doesn't show moved sections in code. Try WinMerge.org or CodeCompare tools with option to detect moved sections turned on

**Comment by jphellemons** [comment]
Thank you for your effort! I have made a new branch for some unit tests. To keep track of the consistency of the library and included your changes there.

**Comment by birbilis** [comment]
hi, are these now in the main branch too? (hadn't done any external API modifications, so all should be OK)

**Pull request closed without merging**
